version: '3.8'

services:
  maria:
    image: mariadb:10
    container_name: maria-webflux
    restart: always
    ports:
      - "3310:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: "password"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 27017
      MONGO_INITDB_ROOT_PASSWORD: password